### ISSUE TITLE
rsolr-ext doesn't seem to work with current solr install

### ISSUE THREAD

**Issue by rb2k** [mwmitchell/rsolr-ext#8]
```
ruby-1.9.2-p136 :001 > require "rsolr-ext"
 => true 
ruby-1.9.2-p136 :002 > solr_connection = RSolr.connect
 => #<RSolr::Client:0x00000101988e68 @connection=#<RSolr::Connection:0x00000101988e90>, @uri=#<URI::HTTP:0x000001019de9d0 URL:http://127.0.0.1:8983/solr/>, @options={}> 
ruby-1.9.2-p136 :003 > puts solr_connection.luke['fields'].inspect
ArgumentError: wrong number of arguments (3 for 2)
    from /Users/mseeger/.rvm/gems/ruby-1.9.2-p136/gems/rsolr-1.0.0/lib/rsolr/client.rb:144:in `send_and_receive'
    from /Users/mseeger/.rvm/gems/ruby-1.9.2-p136/gems/rsolr-1.0.0/lib/rsolr/client.rb:222:in `method_missing'
    from /Users/mseeger/.rvm/gems/ruby-1.9.2-p136/gems/rsolr-1.0.0/lib/rsolr/pagination.rb:54:in `method_missing'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p136/gems/rsolr-ext-0.12.1/lib/rsolr-ext/client.rb:38:in `luke'
from (irb):3
from /Users/mseeger/.rvm/rubies/ruby-1.9.2-p136/bin/irb:16:in `<main>'
```

It works on gem 0.12.1

**Comment by mwmitchell** [comment]
Hi, Please try this with rsolr-ext 1.0.0 instead of 0.12.1. Let me know how that goes.

Matt

**Comment by rb2k** [comment]
Thanks, after uninstalling rsolr-ext-0.12.1 it worked. I wonder why it prefered 0.12.1 to 1.0.0 when doing the 'require'
